//------------------------------------------------------------------------------
// <auto-generated>
//     このコードはツールによって生成されました。
//     ランタイム バージョン:4.0.30319.42000
//
//     このファイルへの変更は、以下の状況下で不正な動作の原因になったり、
//     コードが再生成されるときに損失したりします。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Toml.Properties {
    using System;
    
    
    /// <summary>
    ///   ローカライズされた文字列などを検索するための、厳密に型指定されたリソース クラスです。
    /// </summary>
    // このクラスは StronglyTypedResourceBuilder クラスが ResGen
    // または Visual Studio のようなツールを使用して自動生成されました。
    // メンバーを追加または削除するには、.ResX ファイルを編集して、/str オプションと共に
    // ResGen を実行し直すか、または VS プロジェクトをビルドし直します。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   このクラスで使用されているキャッシュされた ResourceManager インスタンスを返します。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Toml.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   厳密に型指定されたこのリソース クラスを使用して、すべての検索リソースに対し、
        ///   現在のスレッドの CurrentUICulture プロパティをオーバーライドします。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   日付が解析できない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ANALISYS_DATE_ERR {
            get {
                return ResourceManager.GetString("ANALISYS_DATE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー／値解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ANALISYS_KEY_VALUE_ERR {
            get {
                return ResourceManager.GetString("ANALISYS_KEY_VALUE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時差が解析できない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ANALISYS_TIME_DIFF_ERR {
            get {
                return ResourceManager.GetString("ANALISYS_TIME_DIFF_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   時間が解析できない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ANALISYS_TIME_ERR {
            get {
                return ResourceManager.GetString("ANALISYS_TIME_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配列が正しく閉じられていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ARRAY_NOT_CLOSE_ERR {
            get {
                return ResourceManager.GetString("ARRAY_NOT_CLOSE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   配列内の値の型が異なる に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ARRAY_VALUE_DIFFERENT_ERR {
            get {
                return ResourceManager.GetString("ARRAY_VALUE_DIFFERENT_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キーが再定義された に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DEFINED_KEY_ERR {
            get {
                return ResourceManager.GetString("DEFINED_KEY_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   実数値が有効範囲を超えている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string DOUBLE_VALUE_RANGE_ERR {
            get {
                return ResourceManager.GetString("DOUBLE_VALUE_RANGE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   カンマの前に値が定義されていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMPTY_COMMA_ERR {
            get {
                return ResourceManager.GetString("EMPTY_COMMA_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   空値はインデックスアクセスできない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string EMPTY_VAL_INDEX_ERR {
            get {
                return ResourceManager.GetString("EMPTY_VAL_INDEX_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   {0} 行:{1} 列:{2} に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ERR_MSG_TEMPLATE {
            get {
                return ResourceManager.GetString("ERR_MSG_TEMPLATE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   添え字が範囲外 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INDEX_OUT_RANGE {
            get {
                return ResourceManager.GetString("INDEX_OUT_RANGE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   インラインテーブルが正しく閉じられていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INLINE_TABLE_NOT_CLOSE_ERR {
            get {
                return ResourceManager.GetString("INLINE_TABLE_NOT_CLOSE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   整数値が有効範囲を超えている に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INTEGER_VALUE_RANGE_ERR {
            get {
                return ResourceManager.GetString("INTEGER_VALUE_RANGE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   無効なエスケープ文字が指定された に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string INVALID_ESCAPE_CHAR_ERR {
            get {
                return ResourceManager.GetString("INVALID_ESCAPE_CHAR_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   キー文字列の解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEY_ANALISYS_ERR {
            get {
                return ResourceManager.GetString("KEY_ANALISYS_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値の解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string KEY_VALUE_ERR {
            get {
                return ResourceManager.GetString("KEY_VALUE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   リテラル文字列定義エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string LITERAL_STRING_ERR {
            get {
                return ResourceManager.GetString("LITERAL_STRING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数の小数点が定義された に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MULTI_DECIMAL_ERR {
            get {
                return ResourceManager.GetString("MULTI_DECIMAL_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数リテラル文字列定義エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MULTI_LITERAL_STRING_ERR {
            get {
                return ResourceManager.GetString("MULTI_LITERAL_STRING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   複数クォーテーション文字列定義エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string MULTI_QUOAT_STRING_ERR {
            get {
                return ResourceManager.GetString("MULTI_QUOAT_STRING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小数点の後に数値が入力されていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_LAST_ZERO_ERR {
            get {
                return ResourceManager.GetString("NO_LAST_ZERO_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   小数点の前に数値が入力されていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NO_LEADING_ZERO_ERR {
            get {
                return ResourceManager.GetString("NO_LEADING_ZERO_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   値が定義されていない に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string NOT_DEFINED_VALUE_ERR {
            get {
                return ResourceManager.GetString("NOT_DEFINED_VALUE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   文字列定義エラー に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string QUOAT_STRING_ERR {
            get {
                return ResourceManager.GetString("QUOAT_STRING_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   既に同キーが登録されています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string REREGIST_KEY_ERR {
            get {
                return ResourceManager.GetString("REREGIST_KEY_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル配列構文の解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TABLE_ARRAY_SYNTAX_ERR {
            get {
                return ResourceManager.GetString("TABLE_ARRAY_SYNTAX_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル名を再定義しています に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TABLE_REDEFINITION_ERR {
            get {
                return ResourceManager.GetString("TABLE_REDEFINITION_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   テーブル構文の解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string TABLE_SYNTAX_ERR {
            get {
                return ResourceManager.GetString("TABLE_SYNTAX_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値定義に連続してアンダーバーが使用された に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNDERBAR_CONTINUE_ERR {
            get {
                return ResourceManager.GetString("UNDERBAR_CONTINUE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   ユニコード文字定義の解析に失敗 に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string UNICODE_DEFINE_ERR {
            get {
                return ResourceManager.GetString("UNICODE_DEFINE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Tomlデータの型が使用できません に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string USED_VALUE_TYPE_ERR {
            get {
                return ResourceManager.GetString("USED_VALUE_TYPE_ERR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   数値の先頭に無効な 0がある に類似しているローカライズされた文字列を検索します。
        /// </summary>
        internal static string ZERO_NUMBER_ERR {
            get {
                return ResourceManager.GetString("ZERO_NUMBER_ERR", resourceCulture);
            }
        }
    }
}
